import random


def test_lottery_generator(iterations_limit, denominator):
	trueCounter = 0
	flaseCounter = 0

	for i in range(0, iterations_limit):
		x = lottery_generator(denominator)
		if x:
			trueCounter += 1
		else:
			flaseCounter += 1

	print("True count: {} False count: {}".format(trueCounter/iterations_limit, flaseCounter/iterations_limit))



def lottery_generator(rangeEnd) -> bool:
	rangeStart = 1
	x = random.randint(rangeStart, rangeEnd)
	if rangeStart == x:
		return True
	else:
		return False


def check_uniform_distribution(rangeStart, rangeEnd, iterations_limit):
	int_buckets_array = [0 for x in range(rangeStart, rangeEnd + 1)]

	num_of_iterations = iterations_limit;
	print('checking Uniform Distribution')
	print('iterations limit: {}'.format(iterations_limit));

	for i in range(0, num_of_iterations) :
		x = random.randint(rangeStart, rangeEnd)
		#print(x)
		int_buckets_array[x - 1] += 1
	
	print('finished generation. Dumping Result')

	sum = 0
	for i in range(rangeStart, rangeEnd + 1) : 
		print("{} : {}".format(i, int_buckets_array[i]/(iterations_limit/10)))
		sum += int_buckets_array[i]

	print('checksum: {}'.format(sum))


def test_static_distribution_full_day():
	### FULL DAY ###

	amount_of_prizes = 100
	amount_of_users_day = 24000

	rng_denominator = round(amount_of_users_day / amount_of_prizes)
	prizes_given_counter = 0

	for i in range(0, amount_of_users_day):
		x = lottery_generator(rng_denominator)
		if x:
			prizes_given_counter += 1

	print("amount_of_users_day: {} prizes_given_counter: {}".format(amount_of_users_day, prizes_given_counter))

def test_statis_distribution_multiple_intervals():
	#iterations_limit = 10000;

	# rangeStart = 0
	# rangeEnd = 9
	# check_uniform_distribution(rangeStart, rangeEnd, iterations_limit)

	#test_lottery_generator(iterations_limit, 2)


	### DAY SPLIT IN HALFS ###

	# amount_of_prizes_intervas_array = [50, 50]
	# amount_of_users_intervals_array = [12000, 12000]

	### DAY SPLIT BY HOUR ###

	# MAIN SETTINGS
	time_intervals_count = 24 #hours
	total_amount_of_prizes = 100 #total prizes per 24h
	total_amount_of_users_day = 24000 #now isn't used

	# PRIZES
	amount_of_prizes_intervas_array = [round(total_amount_of_prizes/time_intervals_count) for x in range(0, time_intervals_count)]

	# USERS
	#amount_of_users_intervals_array = [round(total_amount_of_users_day/time_intervals_count) for x in range(0, time_intervals_count)]

	# RANDOMLY GENERATED by [random.randint(500, 1500) for x in range(0, time_intervals_count)]
	amount_of_users_intervals_array = [1496, 1026, 1284, 969, 870, 923, 977, 579, 1347, 656, 984, 1075, 939, 601, 1044, 1324, 634, 616, 518, 1443, 1209, 1306, 1267, 544]

	rng_denominator_array = [round(amount_of_users_intervals_array[i]/amount_of_prizes_intervas_array[i]) for i in range(0, time_intervals_count)]
	prizes_given_counter_array = [0 for x in range(0, time_intervals_count)]

	for ti_idx in range(0, time_intervals_count):
		for i in range(0, amount_of_users_intervals_array[ti_idx]):
			x = lottery_generator(rng_denominator_array[ti_idx])
			if x:
				prizes_given_counter_array[ti_idx] += 1

	for ti_idx in range(0, time_intervals_count):
		print("ti_idx: {} amount_of_users: {} prizes_given: {} with prize probability: 1/{}".
			format(ti_idx, 
				amount_of_users_intervals_array[ti_idx], 
				prizes_given_counter_array[ti_idx], 
				rng_denominator_array[ti_idx]))

	total_prizes_given = sum(prizes_given_counter_array)
	print("total prizes given: {}".format(total_prizes_given))

######### MAIN CODE #########

# MAIN SETTINGS
time_intervals_count = 24 #hours
total_amount_of_prizes = 100 #total prizes per 24h
total_amount_of_users_day = 24000 #now isn't used

# PRIZES
amount_of_prizes_intervas_array = [round(total_amount_of_prizes/time_intervals_count) for x in range(0, time_intervals_count)]
prizes_given_counter_array = [0 for x in range(0, time_intervals_count)]

assumed_amount_of_users_intervals_array = [1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
actual_amount_of_users_intervals_array = [1496, 1026, 1284, 969, 870, 923, 977, 579, 1347, 656, 984, 1075, 939, 601, 1044, 1324, 634, 616, 518, 1443, 1209, 1306, 1267, 544]

assumed_rng_denominator_array = [0 for i in range(0, time_intervals_count)]

for ti_idx in range(0, time_intervals_count):
	# Initial lottery based on assumed number of incoming users

	assumed_rng_denominator_array[ti_idx] = round(assumed_amount_of_users_intervals_array[ti_idx]/amount_of_prizes_intervas_array[ti_idx])
	for i in range(0, actual_amount_of_users_intervals_array[ti_idx]):
		x = lottery_generator(assumed_rng_denominator_array[ti_idx])
		if x:
			prizes_given_counter_array[ti_idx] += 1

	# NOW we have actual users who came - time to update our assumptions
	if ti_idx < time_intervals_count - 1: #check to avoid out of bounds
		assumed_amount_of_users_intervals_array[ti_idx + 1] = actual_amount_of_users_intervals_array[ti_idx]

	# and on it goes

for ti_idx in range(0, time_intervals_count):
	print("ti_idx: {}	ASSUMED #users: {}	ACTUAL #users: {}	prizes_given: {}	ASSUMED prize probability: 1/{}".
		format(ti_idx, 
			assumed_amount_of_users_intervals_array[ti_idx], 
			actual_amount_of_users_intervals_array[ti_idx], 
			prizes_given_counter_array[ti_idx], 
			assumed_rng_denominator_array[ti_idx]))

total_prizes_given = sum(prizes_given_counter_array)
print("total prizes given: {}".format(total_prizes_given))



